### ISSUE TITLE
Generic Exception "Please verify server_context is configured correctly."

### ISSUE THREAD

**Issue by thusharaw** [LabKey/labkey-api-python#12]
If a database insert fails, we get a generic error > Please verify server_context is configured correctly.

Ex:

Doing an insert with a duplicate constraint results in:
[WARNING: 240 2018-01-30 15:19:08,152] cannot insert plate 3500001280 because 'Please verify server_context is configured correctly.'

Grabbing the e.\_\_context\_\_ shows the actual exception:

[WARNING: 334 2018-01-30 15:18:32,451] could not add plate 3500001280 because '400: ERROR: duplicate key value violates unique constraint "uq_plate_barcode"\n  Detail: Key (barcode)=(3500001280) already exists.'

I think this is because here:

https://github.com/LabKey/labkey-api-python/blob/2338b74e209d075868269d7bb322b92ff14b81ad/labkey/utils.py#L68

and here:

https://github.com/LabKey/labkey-api-python/blob/2338b74e209d075868269d7bb322b92ff14b81ad/labkey/exceptions.py#L72

the original exception is being swallowed.

replacing this:
return switcher.get(type(e), 'Please verify server_context is configured correctly.')

with:
return switcher.get(type(e), str(e) if str(e) else 'Please verify server_context is configured correctly.')

should allow the user to see the original exception.

**Comment by labkey-nicka** [comment]
Fixed with PR #13. Thanks!
