### ISSUE TITLE
Update README with instructions for testing

### ISSUE THREAD

**Issue by mikkel14** [LabKey/labkey-api-python#18]
Thought I would share some modifications that I had to make in order to quickly start up a development environment for this project.

Using pip to install the package with `setup.py` was working, but it was not installing the dependency in the `tests_require` variable. The dependencies in that variable would be installed when testing through setuptools, but the current example in `README.md` is running them manually. A small modifications to `setup.py`. Your testing workflow may be different, but I wanted to chime in anyway. Thanks!

**Comment by labkey-alan** [comment]
This has been addressed with #24
