### ISSUE TITLE
'is[non]blank' query filter types are missing from `QueryFilter.Types`

### ISSUE THREAD

**Issue by AetherUnbound** [LabKey/labkey-api-python#22]
When using the UI, we can filter columns by "Is Blank" and "Is Not Blank". When using the export to python function, it produces code that looks like this:
```python
my_results = labkey.query.select_rows(
    server_context=server_context,
    schema_name='microscopy',
    query_name='Plate',
    filter_array=[
        labkey.query.QueryFilter('Comments', '', 'isnonblank')
    ]
)
```
and
```python
my_results = labkey.query.select_rows(
    server_context=server_context,
    schema_name='microscopy',
    query_name='Plate',
    filter_array=[
        labkey.query.QueryFilter('Comments', '', 'isblank')
    ]
)
```

It looks like `isblank` and `isnonblank` [are not present in the `QueryFilter.Types` enum](https://github.com/LabKey/labkey-api-python/blob/master/labkey/query.py#L304-L351)

**Comment by AetherUnbound** [comment]
I think we may be able to submit a PR for this, first come first serve :grin:

**Comment by jnicholas** [comment]
@AetherUnbound These export functions are produced in Java code. I think the fix for this would be in:

https://github.com/LabKey/platform/blob/develop/api/src/org/labkey/api/query/PythonExportScriptModel.java

or in a usage of that class.

**Comment by AetherUnbound** [comment]
Oh I don't think a change needs to be made to the export functions - the `isblank` and `isnonblank` filter types just don't exist in the Python API under `QueryFilter::Types`
